package com.example.demo;

import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.bson.types.ObjectId;

//same as frontend ticketDetails
@Data
@NoArgsConstructor
@AllArgsConstructor

//to create ticket
public class TicketDetails {
    //no need referenceNo, generated by backend
    private String seatNumber;  //Eg. "D6"
    private ObjectId movie;
    private ObjectId user;
    private ObjectId room;
    private String ticketType;
    private double price;
}
