package cinemabookingsystem.model;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.mongodb.core.mapping.Document;

import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.List;

//auto generates getters setters
@Data
@NoArgsConstructor
@AllArgsConstructor

@Document(collection = "cart")
public class ShoppingCart {
    private String id;    //auto generated by mongoDG
    private String userId;
    @JsonProperty
    private boolean isCheckedOut;
    private List<String> ticketIds;     //each shopping cart can have >1 ticket
    private List<String> foodDrinkIds;  //same for foodDrinks
    private List<String> rewardIds;     //same for rewards

    public ShoppingCart(String userId, boolean isCheckedOut, List<String> ticketIds, List<String> foodDrinkIds, List<String> rewardIds) {
        this.userId = userId;
        this.isCheckedOut = isCheckedOut;
        this.ticketIds = ticketIds;
        this.foodDrinkIds = foodDrinkIds;
        this.rewardIds = rewardIds;
    }

    public boolean getIsCheckedOut() {
        return isCheckedOut;
    }

    public void setIsCheckedOut(boolean isCheckedOut) {
        this.isCheckedOut = isCheckedOut;
    }
}